version: '3'

volumes:
  postgres_data: { }

services:
  postgres:
    container_name: "bun-postgres"
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
